$ToRemove = @('TestAccountUserCustomerUser.role'
,'TestAccountAdminCustomerUser.role'
,'ProfileSkillUser-Skill User Layout.layout'
,'ProfileSkillEndorsement-Endorsement Layout.layout'
,'ProfileSkill-Skill Layout.layout'
,'SocialPost-Social Post Layout.layout'
,'WorkThanks-Thanks Layout.layout'
,'WorkBadgeDefinition-Badge Layout.layout'
,'WorkBadge-Badge Received Layout.layout'
,'workAccess-Access Layout.layout'
,'Bosch_Force.app'
,'standard__DataAssessment.app'
,'Standard_Reports_Dashboard.dashboard'
,'Risk_Factor_Breakdown.dashboard'
,'standard__Work.app'
,'Maxwell_Force.app'
,'Questions_Answers.app'
,'Coaching.app'
,'Client_Admin.app'
,'ABC_Company_Portal.app'
,'Security.settings'
,'mxw__Activity__c.object'
,'mxw__Page_Section_Joiner__c.object'
,'mxw__Progress__c.object'
,'mxw__Relationship__c.object'
,'mxw__Section_Progress__c.object'
,'mxw__Section__c.object'
,'mxw__Wellness_Event_Appointment__c.object'
,'Admin.profile'
,'Analytics Cloud Integration User.profile'
,'Analytics Cloud Security User.profile'
,'Authenticated Website.profile'
,'Chatter External User.profile'
,'Chatter Free User.profile'
,'Chatter Moderator User.profile'
,'Chatter Only User.profile'
,'ContractManager.profile'
,'Cross Org Data Proxy User.profile'
,'Custom%3A Marketing Profile.profile'
,'Custom%3A Sales Profile.profile'
,'Custom%3A Support Profile.profile'
,'Customer Community Login User.profile'
,'Customer Community Plus Login User.profile'
,'Customer Community Plus User.profile'
,'Customer Community User.profile'
,'Customer Portal Manager Custom.profile'
,'Customer Portal Manager Standard.profile'
,'CustomerManager.profile'
,'External Identity User.profile'
,'Force%2Ecom - App Subscription User.profile'
,'Force%2Ecom - Free User.profile'
,'Gold Partner User.profile'
,'Guest.profile'
,'High Volume Customer Portal User.profile'
,'HighVolumePortal.profile'
,'Identity User.profile'
,'MarketingProfile.profile'
,'Overage Customer Portal Manager Custom.profile'
,'Overage Customer Portal Manager Standard.profile'
,'Overage High Volume Customer Portal User.profile'
,'Partner App Subscription User.profile'
,'Partner Community Login User.profile'
,'Partner Community User.profile'
,'Partner.profile'
,'PlatformPortal.profile'
,'ReadOnly.profile'
,'ServiceCloud.profile'
,'Silver Partner User.profile'
,'SolutionManager.profile'
,'Standard Community User.profile'
,'Standard.profile'
,'StandardAul.profile'
,'test Profile.profile'
,'Work%2Ecom Only User.profile'
,'PVT CSR.profile'
,'Performance_Cycles_with_Questions.reportType'
,'Performance_Summary_Cycles_with_Requests.reportType'
,'Performance_Summary_Requests_with_Answers.reportType'
,'Performance_summary_users_with_managers.reportType'
,'Thanks_and_Badges.reportType'
,'Goals.reportType'
,'Goals_and_Metrics.reportType'
,'Goals_Feed.reportType'
,'AAAAdminCustomerUser.role'
,'AAACustomerUser.role'
,'ACHCustomerUser.role'
,'ACHreportingCustomerUser.role'
,'AcuityBrandsIncCustomerUser.role'
,'ArrowCustomerUser.role'
,'AscensionCustomerUser.role'
,'AscensionHealthCustomerUser.role'
,'AscensionReportingCustomerUser.role'
,'BCBSRICustomerUser.role'
,'BOMCustomerUser.role'
,'BoschCustomerUser.role'
,'BostonCustomerUser.role'
,'BrownCustomerUser.role'
,'BrunswickCustomerUser.role'
,'CapellaCustomerUser.role'
,'CarMaxCustomerUser.role'
,'CatholicHealthInitiativesCustomerUser.role'
,'CatholicHealthInitiativesStJosephsCustomerUser.role'
,'CGBEnterprisesIncCustomerUser.role'
,'ChannelSalesTeam.role'
,'CHICustomerManager.role'
,'CHICustomerUser.role'
,'CLIENTADMINZCustomerUser.role'
,'CommerceCustomerUser.role'
,'Community_User.role'
,'CFO.role'
,'COO.role'
,'CORTCustomerUser.role'
,'CoventryCustomerManager.role'
,'CoventryCustomerUser.role'
,'CrawfordCompanyCustomerUser.role'
,'CreeCustomerUser.role'
,'CreeDurhamCustomerUser.role'
,'CRWCustomerUser.role'
,'CustomerSupportInternational.role'
,'CustomerSupportNorthAmerica.role'
,'CWPUCustomerUser.role'
,'danieltestaccountCustomerUser.role'
,'DirectorChannelSales.role'
,'DirectorDirectSales.role'
,'DormanAdminCustomerUser.role'
,'DormanCustomerUser.role'
,'EasternSalesTeam.role'
,'EEPCACustomerManager.role'
,'EEPCACustomerUser.role'
,'EnbridgeCustomerUser.role'
,'EricssonCustomerUser.role'
,'FirstHorizonCustomerUser.role'
,'FrontierCustomerUser.role'
,'FrostCustomerUser.role'
,'GGPCustomerManager.role'
,'GGPCustomerUser.role'
,'GGPWellnessChampsCustomerManager.role'
,'GGPWellnessChampsCustomerUser.role'
,'GlacierCustomerUser.role'
,'HarrisCustomerUser.role'
,'HealthNowCustomerUser.role'
,'HenkelCustomerUser.role'
,'HillRomCustomerUser.role'
,'HMHCustomerUser.role'
,'HMHCustomerUser1.role'
,'HunterDouglasCustomerUser.role'
,'HunterDouglasCustomerUser1.role'
,'ICAGCustomerUser.role'
,'InstallationRepairServices.role'
,'JackHenryCustomerUser.role'
,'JohnsonCountyCustomerUser.role'
,'JourneyTestCustomerManager.role'
,'JourneyTestCustomerUser.role'
,'LamarAdvertisingCompanyCustomerUser.role'
,'LamarCustomerUser.role'
,'LICCustomerUser.role'
,'MarketingTeam.role'
,'MercedesBenzfemaleCustomerUser.role'
,'MercedezBenzMaleCustomerUser.role'
,'MillerCoorsCustomerUser.role'
,'NEWHIRECustomerUser.role'
,'OaktreeCapitalManagementLPCustomerUser.role'
,'OctapharmaCustomerUser.role'
,'OctapharmaReportingCustomerUser.role'
,'ParexelCustomerUser.role'
,'PAWCustomerUser.role'
,'PAWWellnessChampCustomerUser.role'
,'PDRCustomerUser.role'
,'PFJCustomerUser.role'
,'PreventureCustomerUser.role'
,'PVTCustomerUser.role'
,'PVTGMCustomerUser.role'
,'PVTSalesCustomerUser.role'
,'PVTSalesDemoCustomerUser.role'
,'PVTSalesDemowithReportingCustomerUser.role'
,'RBTCustomerUser.role'
,'Release3CustomerManager.role'
,'Release3CustomerUser.role'
,'Release3NoConnectCustomerManager.role'
,'Release3NoConnectCustomerUser.role'
,'RNDCustomerUser.role'
,'RobertBoschLLCCustomerUser.role'
,'RoundysCustomerUser.role'
,'SEICustomerUser.role'
,'SpartanNashCustomerUser.role'
,'SprintCustomerUser.role'
,'SubaruCustomerUser.role'
,'SVPCustomerServiceSupport.role'
,'SVPHumanResources.role'
,'SVPSalesMarketing.role'
,'Test_Client_Org_1.role'
,'testCustomerUser.role'
,'TestPortalAccountCustomerUser.role'
,'TMKCustomerUser.role'
,'UAT_Testing_Account_Admins_Customer_User.role'
,'UATTest1AcctChampsAdminCustomerManager.role'
,'UATTest1AcctChampsAdminCustomerUser.role'
,'UATTest1AcctCustomerUser.role'
,'UATTestingAccountAdminsCustomerUser.role'
,'UATTestingAccountCustomerUser.role'
,'VarsityBSNCustomerUser.role'
,'VarsityHerffJonesCustomerUser.role'
,'VPInternationalSales.role'
,'VPMarketing.role'
,'VPNorthAmericanSales.role'
,'WaupacaFoundryIncAdminCustomerUser.role'
,'WaupacaFoundryIncCustomerUser.role'
,'WesternSalesTeam.role'
,'WFICustomerManager.role'
,'WFICustomerUser.role'
,'WFIWellnessChampsCustomerManager.role'
,'WFIWellnessChampsCustomerUser.role'
,'WhataburgerCustomerUser.role'
,'WhataburgerNoReportingCustomerUser.role'
,'test.reportType'
,'Reward_Funds.reportType'
,'Account-Account %28Marketing%29 Layout'
,'Account-Account %28Sales%29 Layout'
,'Account-Account %28Support%29 Layout'
,'Asset-Asset Layout'
,'Campaign-Campaign Layout'
,'CampaignMember-Campaign Member Page Layout'
,'Case-Case %28Marketing%29 Layout'
,'Case-Case %28Sales%29 Layout'
,'Case-Case %28Support%29 Layout'
,'Case-Case Layout'
,'CaseClose-Close Case Layout'
,'CaseInteraction-Case Feed Layout'
,'CollaborationGroup-Group Layout'
,'Contact_Snapshot__c-Contact Snapshot Layout'
,'Contact-Contact %28Marketing%29 Layout'
,'Contact-Contact %28Sales%29 Layout'
,'Contact-Contact %28Support%29 Layout'
,'ContentVersion-Content Version Layout'
,'ContentVersion-General'
,'Contract-Contract Layout'
,'DandBCompany-D%26B Company Layout'
,'DuplicateRecordSet-Duplicate Record Set Layout'
,'FeedItem-Feed Item Layout'
,'Goal-Goal Layout'
,'GoalLink-Goal Link Layout'
,'Idea-Idea Layout'
,'JobTracker-Job Tracker Layout'
,'JobTracker-Job Tracker Layout - Summer %2715'
,'JobTracker-Job Tracker Layout - Winter %2716'
,'Lead-Lead %28Marketing%29 Layout'
,'Lead-Lead %28Sales%29 Layout'
,'Lead-Lead %28Support%29 Layout'
,'Lead-Lead Layout'
,'Macro-Macro Layout'
,'OpportunityLineItem-Opportunity Product Layout'
,'Opportunity-Opportunity %28Marketing%29 Layout'
,'Opportunity-Opportunity %28Sales%29 Layout'
,'Opportunity-Opportunity %28Support%29 Layout'
,'Opportunity-Opportunity Layout'
,'OrderItem-Order Product Layout'
,'Order-Order Layout'
,'Pricebook2-Price Book Layout'
,'PricebookEntry-Price Book Entry'
,'PricebookEntry-Price Book Entry Layout'
,'Product2-Product Layout'
,'SocialPersona-Social Persona Layout'
,'Solution-Solution Layout'
,'SOSSessionActivity-SOS Session Activity Layout'
,'SOSSession-SOS Session Layout'
,'Task-Task Layout'
,'WorkCoaching-Coaching Layout'
,'WorkCoaching-Coaching Layout 194'
,'WorkCoaching-Coaching Layout 2%2E0'
,'WorkFeedback-Feedback Layout'
,'WorkFeedback-Feedback Layout - Summer %2715'
,'WorkFeedback-Feedback Layout - Winter %2716'
,'WorkFeedbackQuestion-Feedback Question Layout'
,'WorkFeedbackQuestion-Feedback Question Layout - Summer %2715'
,'WorkFeedbackQuestion-Feedback Question Layout - Winter %2716'
,'WorkFeedbackQuestionSet-Feedback Question Set Layout'
,'WorkFeedbackQuestionSet-Feedback Question Set Layout - Summer %2715'
,'WorkFeedbackQuestionSet-Feedback Question Set Layout - Winter %2716'
,'WorkFeedbackRequest-Feedback Request Layout'
,'WorkFeedbackRequest-Feedback Request Layout - Summer %2715'
,'WorkFeedbackRequest-Feedback Request Layout - Winter %2716'
,'WorkFeedbackTemplate-Feedback Template Layout'
,'WorkPerformanceCycle-Performance Cycle Layout'
,'WorkPerformanceCycle-Performance Cycle Layout - Summer %2715'
,'WorkPerformanceCycle-Performance Cycle Layout - Winter %2716'
)

foreach ($item in $ToRemove) {
    Remove-Item c:\users\vgebhart\documents\metadatas\* -recurse -include $item -verbose | Tee-Object c:\temp\purge.txt
    Remove-Item c:\users\vgebhart\documents\metadatas_master\* -recurse -include $item -verbose | Tee-Object c:\temp\purge.txt
}

